Repository aertslab/SCope, pull requests merged in 2021-07, with the labels that each got.

#452 Cleanup/373 Frontend Stage 4 - ViewerSideBar
  .nvmrc
  src/components/ClusterControls/UpdateClusterDescriptionInput.tsx
  src/components/ClusterControls/index.tsx
  src/components/CommunityAnnotationTable/components/CuratorTableCell.tsx
  src/components/CommunityAnnotationTable/components/OBOTableCell.tsx
  src/components/CommunityAnnotationTable/components/VotesTableCell.tsx
  src/components/CommunityAnnotationTable/constants.ts
  src/components/CommunityAnnotationTable/index.tsx
  src/components/CommunityAnnotationTable/model.ts
  src/components/FeatureMarkerTable/components/MarkerTableGeneCell.tsx
  src/components/FeatureMarkerTable/index.tsx
  src/components/FeatureMarkerTable/model.ts
  src/components/GProfiler/GProfilerModal.tsx
  src/components/GProfiler/sagas.ts
  src/components/LassoControls/LassoSelectionPane.tsx
  src/components/LassoControls/index.tsx
  src/components/LassoControls/model.ts
  src/components/LegendTable/index.tsx
  src/components/LegendTable/model.ts
  src/components/MotifLogo/index.tsx
  src/components/MotifLogo/model.ts
  src/components/QueryFeatureMetadata/index.tsx
  src/components/QueryFeatureTool/EmptyFeatureDisplayMessage.tsx
  src/components/QueryFeatureTool/QueryFeatureTab.tsx
  src/components/QueryFeatureTool/model.ts
  src/components/RightSidebar/index.tsx
  src/components/buttons/DownloadLoomButton.tsx
  src/components/common/CollabAnnoGeneSearch.jsx
  src/components/common/CollaborativeAnnotation.jsx
  src/components/common/Viewer.jsx
  src/components/common/ViewerSidebar.jsx
  src/components/pages/Compare.jsx
  src/components/pages/Gene.jsx
  src/components/pages/Geneset.jsx
  src/components/pages/Regulon.jsx
Labels: enhancement

#453 Closes #431
  src/components/Search/Search.test.ts
  src/components/Search/model.ts
Labels: bug

#457 Convert OLSAutocomplete component to TS
  client/src/components/OLAutocomplete/index.tsx
  client/src/components/common/CollaborativeAnnotation.jsx
Labels: enhancement

#458 Simplify the Compare page select all annotations function
  client/src/components/pages/Compare.jsx
Labels: frontend, low prio

#466 Convert Histogram component to TypeScript
  client/src/components/GProfiler/GProfilerModal.tsx
  client/src/components/GProfiler/model.ts
  client/src/components/Histogram/index.tsx
  client/src/components/Search/FeatureSearch.tsx
  client/src/components/Search/FeatureSearchBox.test.tsx
  client/src/components/Search/FeatureSearchBox.tsx
  client/src/components/Search/actions.ts
  client/src/components/Search/model.ts
  client/src/components/pages/Regulon.jsx
  client/src/model.ts
Labels: enhancement
